### ISSUE TITLE
webhook integration

### ISSUE THREAD

**Issue by xu4wang** [jadolg/RocketChatBot#6]
I noticed the robot is pulling messages every second, while there is a webhook interface from RocketChat, shall we use webhook for better performance?  What do you think the pros/cons between pulling and webhook?

Thanks,
Austin

**Comment by jadolg** [comment]
I have actually not used this strategy for building bots for a long time. Mostly because rocket.chat started limiting the number of API calls you can make in an interval of time, so if your bot is on too many conversations it will eventually start erroring.
I made a bot with the webhooks approach https://github.com/jadolg/annoying_orange_bot but I have not made a lib for that just yet.
With this project I wanted not to do any web hosting, I wanted just to run my bot on my raspberry pi at home without exposing anything to the internet. That's not possible if you use the webhooks approach.

**Comment by xu4wang** [comment]
noted with thank. Will check your annoying orange bot. :-)
